apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-eseries-vp-secret
type: Opaque
stringData:
  username: user
  password: password
  passwordArray: password
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-eseries
spec:
  version: 1
  storageDriverName: eseries-iscsi
  backendName: tbc-eseries-vp
  controllerA: 10.0.0.1
  controllerB: 10.0.0.2
  hostDataIP: 10.0.1.1
  webProxyHostname: 10.0.2.1
  credentials:
    name: backend-tbc-eseries-vp-secret
  defaults:
    size: 10Gi
  labels:
    store: eseries
  region: us-east
  storage:
    - labels:
        performance: gold
        cost: '3'
      zone: us-east-1a
      defaults:
        size: 4Gi
    - labels:
        performance: silver
        cost: '2'
      zone: us-east-1a
      defaults:
        size: 3Gi
    - labels:
        performance: bronze
        cost: '1'
      zone: us-east-1a
      defaults:
        size: 2Gi
  deletionPolicy: retain
