# To regenerate bundle.yaml, from deploy directory run:
# $ kubectl kustomize . > bundle.yaml
#
# Kustomize will merge the specified files also in the correct order.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - podsecuritypolicy_unprivileged.yaml
  - operator.yaml
  - namespace.yaml
  - crds/tridentorchestrator_cr.yaml
