apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-eseries-secret
type: Opaque
stringData:
  username: user
  password: password
  passwordArray: password
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-eseries
spec:
  version: 1
  storageDriverName: eseries-iscsi
  controllerA: 10.0.0.1
  controllerB: 10.0.0.2
  hostDataIP: 10.0.1.1
  webProxyHostname: 10.0.2.1
  credentials:
    name: backend-tbc-eseries-secret
